agendadigital/Controllers/ContactoController.cs
using agendadigital.EntityFramework;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using agendadigital.entidades;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace agendadigital.Controllers
{
    public class ContactoController : Controller
    { 

        private ApplicationDbContext dbContext;
        public ContactoController (ApplicationDbContext applicationDbContext)
        {
            dbContext = applicationDbContext;
        }
    
        // GET: ContactoController
        public async Task<ActionResult> Index()
        {
            var lista = await dbContext.Contactos.ToListAsync();
            return View(lista);
        }

        // GET: ContactoController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            Contacto contacto = await dbContext.Contactos.FindAsync(id);
            return View(contacto);
        }

        // GET: ContactoController/Create
        public async Task<ActionResult> Create()
        {

            ViewBag.UsuarioId = new SelectList(await dbContext.Usuarios.ToListAsync(),"Id","Nombre");
            return View();
        }

        // POST: ContactoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Contacto contacto)
        {
            try
            {
                dbContext.Add(contacto);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ContactoController/Edit/5
        public ActionResult Edit(int id)
        {

            var contacto = dbContext.Contactos.Find(id);
            return View(contacto);
        }

        // POST: ContactoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Contacto contacto)
        {
            try
            {
                if (id != contacto.Id)
                {
                    new Exception("El Id no coincide");
                }
                dbContext.Update(contacto);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(contacto);
            }
        }

        // GET: ContactoController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var contacto = await dbContext.Contactos.FindAsync(id);
            return View(contacto);
        }

        // POST: ContactoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, Contacto contacto)
        {
            try
            {
                dbContext.Remove(contacto);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(contacto);
            }
        }
    }
}

agendadigital/Controllers/TelefonoController.cs
using agendadigital.entidades;
using agendadigital.EntityFramework;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace agendadigital.Controllers
{
    public class TelefonoController : Controller
    {
        private ApplicationDbContext dbContext;
        public TelefonoController(ApplicationDbContext applicationDbContext)
        {
            dbContext =  applicationDbContext;
        }
        // GET: TelefonoController
        public async Task<ActionResult> Index()
        {
            ViewBag.ContactoId = new SelectList(await dbContext.Contactos.ToListAsync(), "Id", "Nombre");
            var lista = await dbContext.Telefonos.ToListAsync();
            return View(lista);
        }

        // GET: TelefonoController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            Telefono telefono = await dbContext.Telefonos.FindAsync(id);
            return View(telefono);
        }

        // GET: TelefonoController/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.ContactoId = new SelectList(await dbContext.Contactos.ToListAsync(), "Id","Nombre"); 
            return View();
        }

        // POST: TelefonoController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Telefono telefono)
        {
            try
            {
                dbContext.Add(telefono);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(telefono);
            }
        }

        // GET: TelefonoController/Edit/5
        public ActionResult Edit(int id)
        {
            var telefono = dbContext.Telefonos.Find(id);
            return View(telefono);
        }

        // POST: TelefonoController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Telefono telefono)
        {
            try
            {
                if (id != telefono.Id)
                {
                    new Exception("El Id no coincide");
                }
                dbContext.Update(telefono);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(telefono);
            }
        }

        // GET: TelefonoController/Delete/5
        public ActionResult Delete(int id)
        {
            var telefono = dbContext.Telefonos.Find(id);
            return View(telefono);
        }

        // POST: TelefonoController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, Telefono telefono)
        {
            try
            {
                dbContext.Remove(telefono);
                await dbContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(telefono);
            }
        }
    }
}

agendadigital/Controllers/UsuarioController.cs
using agendadigital.entidades;
using agendadigital.EntityFramework;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace agendadigital.Controllers
{
    public class UsuarioController : Controller
    {

        private ApplicationDbContext dbContext;
        public UsuarioController(ApplicationDbContext applicationDbContext)
        {
            dbContext = applicationDbContext;
        }

        // GET: UsuarioController
        public async Task<ActionResult> Index()
        {
            var usuarios = await dbContext.Usuarios.ToListAsync();
            return View(usuarios);
        }

        // GET: UsuarioController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            Usuario usuario = await dbContext.Usuarios.FindAsync(id);
            return View(usuario);
        }


        // GET: UsuarioController/Create
        public async Task<ActionResult> Create()
        {

            
            return View();
        }

        // POST: UsuarioController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Usuario usuario)
        {
            try {
                dbContext.Add(usuario);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
                        }

            catch
            {
                return View(usuario);
            }
        }
        // GET: UsuarioController/Edit/5
        public ActionResult Edit(int id)
        {

            var usuario = dbContext.Usuarios.Find(id);
            return View(usuario);
        }

        // POST: UsuarioController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, Usuario usuario)
        {
            try
            {
                if (id != usuario.Id)
                {
                    new Exception("El Id no coincide");
                }
                dbContext.Update(usuario);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(usuario);
            }
        }

        // GET: UsuarioController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var usuario = await dbContext.Usuarios.FindAsync(id);
            return View(usuario);
        }

        // POST: UsuarioController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, Usuario usuario)
        {
            try
            {
                dbContext.Remove(usuario);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(usuario);
            }
        }
    }
}


//ESCRIBI ALGO PARA COMITEAR, DESPUES BORRAR

agendadigital/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - agendadigital</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/agendadigital.styles.css" asp-append-version="true" />
</head>
<body>
    <header style="background:black;">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">agendadigital</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Telefono" asp-action="Index">Telefono</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contacto" asp-action="Index">Contacto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Index">Usuario</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div  class="container">
            &copy; 2022 - agendadigital - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>